### PR TITLE
docs(contributing): Add contributing guide

### PR DESCRIPTION
**Pull request by nicojs**
Add contributing guide in order to welcome newcomers and help them create good PR's
Add readme pointing to the contributing guide.

### CODE REVIEW

**Comment by nicojs** [comment]
@JellePetersHAN would you please also take a look if things are clear for you? Seeing as your a relative newcomer 👍

**Comment by JellePetersHAN** [comment]
It does a great job explaining the current workflow and the examples are a good begin for someone who is new to it, and doesn't know where to start.

However the current contribution guide doesn’t contain any information regarding the structure of the commit messages. Is this by design, seeing as a lot of the commit messages aren’t confirm _the angular commit message style_?

**Comment by nicojs** [comment]
Yeah the angular commit messages are only useful when we're generating the changelog.md directly from commit messages. We're not doing that here. I will add it to the guide.

**Comment by nicojs** [comment]
@JellePetersHAN I hope this clarifies it. Could you take an other look?

**Pull request merged**
