### PR TITLE
Hacktoberfest blog

### PR DESCRIPTION
**Pull request by richardwerkman**

### CODE REVIEW

**Comment by richardwerkman** [comment]
@nicojs @hugo-vrijswijk do you have time to review and add to this PR?

**Comment by hugo-vrijswijk** [comment]
Should there be a separate post for the Stryker.NET release, maybe? It seems like it's worthy of its own blogpost.

Also @nicojs could you add the hacktoberfest results image you showed last week at the top of the post?

**Comment by richardwerkman** [comment]
Yeah we could do that. We've released more features meanwhile. So it's maybe a good idea to split in two blogs

**Comment by nicojs** [comment]
I've added the image and did some rewriting using my Grammarly account. Still need to add the StrykerJS stuff

Yeah, I agree. The Stryker.NET features seem to be a bit out of place here. On the other hand, a dry list of PRs that got merged is also not inspiring. Thoughts?

I'm thinking of spending a paragraph on each PR and being sure to thank the authors that worked on it to emphasize the work everyone put in.

**Comment by rouke-broersma** [comment]
We missed releasing this by just a couple months :) Don't think there's any point anymore unfortunately.

**Pull request closed without merging**
