### PR TITLE
Improve general readability

### PR DESCRIPTION
**Pull request by simondel**
* Use a larger font size for most of the website
* Use a white background
* Condense the overview of blog posts to show grouping
* Use font awesome 5

### CODE REVIEW

**Comment by simondel** [comment]
# Front page
## Current
image
image


## New
image
image

# Blog overview
## Current
image


## New
image

**Comment by Archcry** [comment]
I like it, LGTM.

**Comment by kmdrGroch** [comment]
@simondel [Roboto](https://fonts.google.com/specimen/Roboto) and [Lato](https://fonts.google.com/specimen/Lato) looks really great

**Comment by simondel** [comment]
@kmdrGroch @nicojs Thanks for the feedback! I've switched to Roboto and Lato
image
image
image

**Pull request merged**
