### PR TITLE
Clarify stryker for js and friends

### LINKED ISSUE #96: Navbar - "for javascript"
I've noticed there is ``for Javascript`` in Navbar. But it is also for typescript, angular, react (which is javascript at all but you know).

Maybe instead of ``for javascript`` we should write ``for Web`` or sth like this.
What is your opinion?

### PR DESCRIPTION
**Pull request by nicojs**
Fixes #96

### CODE REVIEW

**Comment by nicojs** [comment]
I've left the navigation bar in tact, instead focusing on the introduction text. 

image

**Comment by nicojs** [comment]
@kmdrGroch does this clarify it for you?

**Comment by kmdrGroch** [comment]
LGTM

**Comment by legopiraat** [comment]
@nicojs I guess it might be off topic but your telling people a lot of languages/frameworks are supported with Stryker.

> Today, Stryker supports most JavaScript projects. It includes support for TypeScript, React, Angular, VueJS, NodeJS and more.

Maybe it would be good to make a page where we list all the frameworks/languages we support. The reason I might like this page is because, `more` at the end of your sentence implies there is more. But people are not able to find what is available at a quick glance. 

For example:

`Stryker.Net` says ` .NET Core 1.1+ only. A .NET Framework 4.5+ version is on the way`
`Stryker4s` says nothing but we do support `Scala 2.11 & 2.12` with 2.13 on its way soon with some blockers at this moment.
`Stryker` says it supports a lot

**Comment by nicojs** [comment]
@legopiraat true. Thanks for feedback.

I've changed it: 
image

**Pull request merged**
