### PR TITLE
docs(blog): add StrykerJS 6 beta article

### PR DESCRIPTION
**Pull request by nicojs**
TODO:

- [ ] Release StrykerJS 6 beta
- [x] Merge https://github.com/stryker-mutator/mutation-testing-elements/pull/1547

### CODE REVIEW

**Comment by nicojs** [comment]
@hugo-vrijswijk whut?

```
2:12:19 PM: stryker-js already exists. Updating...
2:12:19 PM: From https://github.com/stryker-mutator/stryker-js
2:12:19 PM:  * branch            master     -> FETCH_HEAD
2:12:19 PM:    58fc5d3..51308f4  master     -> origin/master
2:12:19 PM: Could not access submodule 'perf/test/express'
```

Maybe we need to clear the netlify cache or something?

**Comment by nicojs** [comment]
Dude, you're telling me you're not using dark mode? 
image

**Comment by hugo-vrijswijk** [comment]
Forgive me for I have sinned! 😱

**Comment by nicojs** [comment]
YOLO!

**Pull request merged**
