### PR TITLE
Add Info Support logo and text

### PR DESCRIPTION
**Pull request by hugo-vrijswijk**
image

Since the Strykerman svg logo doesn't include the 'Powered by Info Support' text anymore I thought it would have a much better place in the footer of the website. So, updated the footer to add the logo that links to the main Info Support website and a 'Powered by' text that links to https://www.infosupport.com/open-source/

@richardwerkman @nicojs @simondel @Mobrockers Thoughts?

### CODE REVIEW

**Comment by richardwerkman** [comment]
Maybe it's an idea to do the footer like this?

2014 - 2021 | Apache 2.0 licence | Website by Stryker team | Designed by Selina van den Top | Powered by (info support logo)

**Comment by Mobrockers** [comment]
I like it

**Comment by hugo-vrijswijk** [comment]
@richardwerkman I'm not sure the Info Support logo in the middle of a line of text would really fit. 

> I like it

@Mobrockers Do you mean Richard's idea or the PR 😅?

**Comment by Mobrockers** [comment]
I like the idea in the pr, logo right in the middle.

**Comment by hugo-vrijswijk** [comment]
Alright, I'll merge this, then. @richardwerkman feel free to make some changes

**Pull request merged**
