### PR TITLE
Add blog article for Stryker 4.0

### PR DESCRIPTION
**Pull request by nicojs**
- Prepare plugin section for stryker 4.0
- Add blog article for Stryker 4

### CODE REVIEW

**Comment by nicojs** [comment]
@gramster @kmdrGroch @Lakitna @brodybits @Garethp I took the liberty of thanking you by name and linking to your GitHub user page. You guys are awesome.

image

Is this OK? Please let me know if you would like your name changed, link changed, or be removed all together.

Feel free to review the blog article 😅. I've planned it for next Wednesday 🤞

**Comment by brodybits** [comment]
Thanks, I think my part was in dumb sledgehammer testing. I will be absent from GitHub this weekend, will try to take a better look on Monday or Tuesday.

**Comment by kmdrGroch** [comment]
@nicojs 
With mutation switching in our backpack, implementing "perTest" coverage analysis for Jest is now on the table, allowing Stryker to run fewer tests in total. See [#2316](https://github.com/stryker-mutator/stryker/issues/2316) for more info.
there you said: "F.y.i: jest is supported in the current beta version (@stryker-mutator/jest-runner@4.0.0-beta.4)"
So are we supporting jest or not? 🤔

**Comment by nicojs** [comment]
>  "F.y.i: jest is supported in the current beta version (@stryker-mutator/jest-runner@4.0.0-beta.4)"

It means that you can use the `@stryker-mutator/jest-runner`, but it doesn't support coverage analysis (either `"perTest"`, or `"all"`, so only `"off"`). You think it needs clarification?

**Comment by kmdrGroch** [comment]
I mean, from what I understood from blog, we don't support 'perTest', and then you link to issue from which I understand sth like "we support Jest since beta4", so I thought you meant 'we support perTest in jest since beta4'. :)

**Comment by nicojs** [comment]
Ah, I understand. I've clarified it a bit in the issue.

**Pull request merged**
