### PR TITLE
Add stryker weekend blog

### PR DESCRIPTION
**Pull request by simondel**

### CODE REVIEW

**Comment by avassem85** [comment]
Ik heb van de namen van de student links naar hun Github account gemaakt en Olaf en Florian waren verwisseld.

**Comment by nicojs** [comment]
If you 2 agree please merge it. I don't have time today to review it, don't let that stop you.

**Comment by avassem85** [comment]
I don't have the rights to do it. "You're not authorized to merge this pull request."

**Comment by simondel** [comment]
Thanks for looking at it @avassem85!

**Pull request merged**
